title: "SeungHyup Baek"
name: "SeungHyup Baek"
position: "M.S. student at Sejong University."
location: "Seoul, Korea"
affiliation: "MMAI, Sejong University"
email: "edwardback@sju.ac.kr"
google_scholar: "https://scholar.google.com/..." 
github: "https://github.com/your-id"
linkedin: "https://www.linkedin.com/in/your-id/"
